//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceCMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public int Id { get; set; }
        public int SupplierSourceId { get; set; }
        public string Logo { get; set; }
        public string Title { get; set; }
        public string CSVUrl { get; set; }
        public int ProductsImported { get; set; }
        public int ProductsNotImported { get; set; }
        public Nullable<System.DateTime> LastDownload { get; set; }
        public System.DateTime Created { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual SupplierSource SupplierSource { get; set; }
    }
}
