//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceCMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Website
    {
        public int Id { get; set; }
        public string Logo { get; set; }
        public string Title { get; set; }
        public string Url { get; set; }
        public string ServerName { get; set; }
        public string DatabaseName { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public System.DateTime Created { get; set; }
        public string CreatedBy { get; set; }
    }
}
